package gr.hua.dit.project.mycitygov.core.service.impl;

import gr.hua.dit.project.mycitygov.core.model.User;
import gr.hua.dit.project.mycitygov.core.model.UserType;
import gr.hua.dit.project.mycitygov.core.port.repository.UserRepository;
import gr.hua.dit.project.mycitygov.core.service.UserBusinessLogicService;
import gr.hua.dit.project.mycitygov.core.service.mapper.UserMapper;
import gr.hua.dit.project.mycitygov.core.service.model.CreateUserRequest;
import gr.hua.dit.project.mycitygov.core.service.model.CreateUserResult;
import gr.hua.dit.project.mycitygov.core.service.model.UserView;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import jakarta.transaction.Transactional;

import java.util.Set;

/**
 * Default implementation of {@link UserBusinessLogicService}.
 */
@Service
public class UserBusinessLogicServiceImpl implements UserBusinessLogicService {

   private static final Logger LOGGER = LoggerFactory.getLogger(UserBusinessLogicServiceImpl.class);

   private final Validator validator;
   private final PasswordEncoder passwordEncoder;
   private final UserRepository userRepository;
   private final UserMapper userMapper;

   public UserBusinessLogicServiceImpl(
         Validator validator,
         PasswordEncoder passwordEncoder,
         UserRepository userRepository,
         UserMapper userMapper) {
      if (validator == null)
         throw new NullPointerException();
      if (passwordEncoder == null)
         throw new NullPointerException();
      if (userRepository == null)
         throw new NullPointerException();
      if (userMapper == null)
         throw new NullPointerException();

      this.validator = validator;
      this.passwordEncoder = passwordEncoder;
      this.userRepository = userRepository;
      this.userMapper = userMapper;
   }

   @Transactional
   @Override
   public CreateUserResult createUser(CreateUserRequest createUserRequest, boolean notify) {
      if (createUserRequest == null) {
         throw new NullPointerException();
      }

      // 1. Validate CreateUserRequest (Bean Validation on DTO)
      // ------------------------------------------------------
      final Set<ConstraintViolation<CreateUserRequest>> requestViolations = this.validator.validate(createUserRequest);

      if (!requestViolations.isEmpty()) {
         final StringBuilder sb = new StringBuilder();
         for (final ConstraintViolation<CreateUserRequest> violation : requestViolations) {
            sb.append(violation.getPropertyPath())
                  .append(": ")
                  .append(violation.getMessage())
                  .append("\n");
         }
         return CreateUserResult.fail(sb.toString());
      }

      // 2. Unpack & normalize input
      // ------------------------------------------------------
      final String afm = createUserRequest.afm().strip();
      final String amka = createUserRequest.amka().strip();
      final String firstName = createUserRequest.firstName().strip();
      final String lastName = createUserRequest.lastName().strip();
      final String email = createUserRequest.email().strip();
      final String phoneNumber = createUserRequest.phoneNumber().strip();
      final String rawPassword = createUserRequest.rawPassword();

      // 3. Business checks (uniqueness)
      // (make sure UserRepository has these methods)
      // ------------------------------------------------------
      if (this.userRepository.existsByEmail(email)) {
         return CreateUserResult.fail("Το email χρησιμοποιείται ήδη.");
      }

      if (this.userRepository.existsByAfm(afm)) {
         return CreateUserResult.fail("Το ΑΦΜ χρησιμοποιείται ήδη.");
      }

      if (this.userRepository.existsByAmka(amka)) {
         return CreateUserResult.fail("Το ΑΜΚΑ χρησιμοποιείται ήδη.");
      }

      // Hash password
      final String hashedPassword = this.passwordEncoder.encode(rawPassword);

      // Instantiate User entity
      User user = new User();
      user.setId(null); // auto-generated by JPA
      user.setAfm(afm);
      user.setAmka(amka);
      user.setFirstName(firstName);
      user.setLastName(lastName);
      user.setEmail(email);
      user.setPhoneNumber(phoneNumber);
      user.setPasswordHash(hashedPassword);
      user.setUserType(UserType.CITIZEN);

      final Set<ConstraintViolation<User>> userViolations = this.validator.validate(user);
      if (!userViolations.isEmpty()) {
         throw new RuntimeException("invalid User instance");
      }

      user = this.userRepository.save(user);

      // TODO will have to use smsPort
      if (notify) {
         LOGGER.info("User registered (AFM={}, AMKA={}, email={})",
               user.getAfm(), user.getAmka(), user.getEmail());
      }

      final UserView userView = this.userMapper.convertUserToUserView(user);

      return CreateUserResult.success(userView);
   }
}
